---
title: 'Metadata for long-term experiments'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- What is metadata?
- Why do we use metadata for?
- What metadata should we collect for LTEs?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Recognise what metadata is.
- Distinguish different types of metadata.
- Understand what makes metadata interoperable.
- Know how to decide what to include in metadata.


::::::::::::::::::::::::::::::::::::::::::::::::

## What is metadata

Metadata is data about the data; metadata provides a description of our data. We need metadata to help us understand the data and how to interpret it. Therefore, metadata plays an important role in making our FAIR.

### Types of metadata
We can distinguish three types of metadata:

__Administrative metadata:__
Information about a project or resource that are relevant for managing it, for example: principle investigator, project collaborators, contacts, funders and grant details, project data management plan, project period, location, etc. This information is usually assigned to the data before you start collecting, but it can change and be added to, so it is important to keep it up to date!

__Descriptive and citation metadata:__
Information about a dataset that allows other researchers to discover and identify it, for example, authors, abstract, keywords, persistent identifier such as a DOI, licence, related publications, and research outputs.

__Structural metadata:__
Information about how the data was created and how it is structured. For example, experiment design and treatment factors, sampling protocols, analytical protocols, measured variables and observations. For an LTE structural metadata can also include information about the experiment management, for example sowing and harvest dates, pest management, tillage and cultivation practice, fertilizer inputs, and environmental information such as soil properties, and climate. Often the difference between metadata and data can be blurred. Structural metadata should be gathered according to best practices used in your research community.

Descriptive and structural metadata should be added continuously throughout the project.

::: discussion 

## Identifying Metadata

For this challenge we'll review the lesson datasets.
- What types of metadata do they collect?
- Are they missing key metadata?
- How consistent are the datasets in their metadata? 
- How do they do they differ?
- Do you think the metadata is FAIR?
:::

### Metadata to describe a long-term experiment

Good metadata are crucial for ensuring LTE data is understandable and therefore reusable by other researchers. The type of metadata collected often depends on the context for the data. Administrative and citation metadata are normally common across different datasets and experiments, for example, a field experiment and a lab experiment will both have information about PIs, funding, abstract, keywords, and identifiers. However, the structural metadata will depend on the context for the experiment and the data, for example, soil chemistry data will need different metadata compared to yield data or diease assessment data


::::::::::::::::::::::::::::::::::::: keypoints 

- Metadata provides essential context for understanding a dataset
- To be reusable, metadata should be consistent across datasets of the same type

::::::::::::::::::::::::::::::::::::::::::::::::

